name: postges-springboot-shopping
services:
  postgres:
    image: debezium/example-postgres:2.3.3.Final
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5444:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks: [postgres-cluster-networks]


  spring-postgres-shopping:
    build: .
    image: spring-postgres-shopping:latest
    ports:
      - 8088:8080
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - JAVA_OPTS=
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - APP.GEMFIRE_REGION_NAME=productsRegion
      - APP.GEMFIRE_LOCATOR_HOST=host.docker.internal
      - APP.GEMFIRE_LOCATOR_PORT=10334
    networks: [postgres-cluster-networks]
    # Uncomment if you want to see logs in your terminal
    # tty: true
    # stdin_open: true

    

networks:
  postgres-cluster-networks:
    driver: bridge

